version: '3.3'
services:
  frontend:
    build:
      context: .
      dockerfile: "./Dockerfile-react"
    volumes:
      - ./go-movie:/go-movie
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    container_name: "frontend"
